# Generated by Django 5.0.2 on 2026-05-14 12:48

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nin', models.CharField(max_length=50, unique=True, verbose_name='National ID')),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(choices=[('MUS', 'Muslim'), ('CHR', 'Christian'), ('OTH', 'Other')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('job_category', models.CharField(choices=[('DRV', 'Driver'), ('DWR', 'Domestic Worker'), ('SEC', 'Security Guard'), ('NAN', 'Nanny'), ('CLN', 'Cleaner'), ('CAR', 'Caregiver')], max_length=3)),
                ('health_clearance', models.BooleanField(default=False)),
                ('yellow_fever_status', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('REG', 'Registered'), ('INT', 'Interviewed'), ('PLC', 'Placed'), ('DOC', 'Documents Sent'), ('VIS', 'Visa Processing'), ('DEP', 'Departed')], default='REG', max_length=3)),
                ('profile_photo', models.ImageField(upload_to=candidates.models.profile_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('passport_copy', models.FileField(upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg'])])),
                ('cv_pdf', models.FileField(upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['job_category', 'application_status'], name='candidates__job_cat_605d30_idx'), models.Index(fields=['date_of_birth'], name='candidates__date_of_c36f8c_idx')],
            },
        ),
    ]
