# Generated by Django 6.0.5 on 2026-05-14 13:14

import candidates.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='e.g., English, Arabic, Swahili', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any medical conditions to note'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_country',
            field=models.CharField(blank=True, help_text='Preferred country in Arab world', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True, help_text='List key skills separated by commas'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='training_certificates',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.document_path),
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('REG', 'Registered'), ('INT', 'Interviewed'), ('MED', 'Medical Pending'), ('MCL', 'Medical Cleared'), ('DOC', 'Documents Sent'), ('VIS', 'Visa Processing'), ('VAP', 'Visa Approved'), ('PLC', 'Placed'), ('DEP', 'Departed'), ('CMP', 'Contract Completed'), ('CAN', 'Cancelled')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='health_clearance',
            field=models.BooleanField(default=False, verbose_name='Health Clearance'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_category',
            field=models.CharField(choices=[('DRV', 'Driver'), ('DWR', 'Domestic Worker'), ('SEC', 'Security Guard'), ('NAN', 'Nanny'), ('CLN', 'Cleaner'), ('CAR', 'Caregiver'), ('HOU', 'Housekeeper'), ('GAR', 'Gardener'), ('COK', 'Cook')], max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.models.profile_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='yellow_fever_status',
            field=models.BooleanField(default=False, verbose_name='Yellow Fever Vaccination'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['passport_number'], name='candidates__passpor_84d93d_idx'),
        ),
    ]
