# Generated by Django 6.0.5 on 2026-05-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_alternative_phone_candidate_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_placed',
            field=models.BooleanField(default=False, verbose_name='Is Placed'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='monthly_salary_placed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Placed Salary'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='placed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Placement Date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='placed_with',
            field=models.CharField(blank=True, max_length=200, verbose_name='Placed With (Employer)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='placement_contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='placement_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Placement Country'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('REG', 'Registered'), ('INT', 'Interviewed'), ('MED', 'Medical Pending'), ('MCL', 'Medical Cleared'), ('DOC', 'Documents Sent'), ('VIS', 'Visa Processing'), ('VAP', 'Visa Approved'), ('PLC', 'Placed - Unavailable'), ('DEP', 'Departed'), ('CMP', 'Contract Completed'), ('CAN', 'Cancelled'), ('UNA', 'Temporarily Unavailable')], default='REG', max_length=3),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
