# Generated by Django 6.0.5 on 2026-05-14 18:10

import candidates.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_is_placed_candidate_monthly_salary_placed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_placed',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='monthly_salary_placed',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='placed_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='placed_with',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='placement_contract_end',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='placement_country',
        ),
        migrations.AddField(
            model_name='candidate',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Issue Date'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('AVA', 'Available'), ('SEL', 'Selected'), ('CAN', 'Cancelled'), ('VIS', 'Visa Issued'), ('REG', 'Registered'), ('INT', 'Interviewed'), ('MED', 'Medical Pending'), ('MCL', 'Medical Cleared'), ('DOC', 'Documents Sent'), ('VPR', 'Visa Processing'), ('PLC', 'Placed'), ('DEP', 'Departed'), ('CMP', 'Contract Completed')], default='AVA', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_category',
            field=models.CharField(choices=[('MAID', 'Maid'), ('CLN', 'Cleaner'), ('CAR', 'Caregiver'), ('DRV', 'Driver'), ('TCH', 'Home Teacher'), ('WTR', 'Waiter'), ('WTS', 'Waitress'), ('NAN', 'Nanny'), ('SEC', 'Security Guard'), ('HOU', 'Housekeeper'), ('GAR', 'Gardener'), ('COK', 'Cook')], max_length=4),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.document_path),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['passport_expiry_date'], name='candidates__passpor_ebdb13_idx'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
