# Generated by Django 6.0.5 on 2026-05-18 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_userprofile_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Client notes about this candidate')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_clients', to='candidates.candidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-selected_at'],
                'unique_together': {('client', 'candidate')},
            },
        ),
    ]
