# Generated by Django 6.0.5 on 2026-05-18 14:19

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_clientselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_video',
            field=models.FileField(blank=True, help_text='Upload a short video introduction of the candidate (max 50MB)', null=True, upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
