# Generated by Django 6.0.5 on 2026-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_candidate_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='health_status',
            field=models.CharField(choices=[('FIT', 'Fit'), ('UNFIT', 'Unfit'), ('PENDING', 'Pending')], default='PENDING', max_length=7, verbose_name='Health Status'),
        ),
    ]
