# Generated by Django 6.0.5 on 2026-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('AVA', 'Available'), ('SEL', 'Selected'), ('CAN', 'Cancelled'), ('VIS', 'Visa Issued'), ('RES', 'ReSERVED')], default='AVA', max_length=3),
        ),
    ]
