# Generated by Django 6.0.5 on 2026-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidate_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientselection',
            name='booking_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientselection',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientselection',
            name='sponsor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientselection',
            name='sponsor_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientselection',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientselection',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('AVA', 'Available'), ('SEL', 'Selected'), ('CAN', 'Cancelled'), ('VIS', 'Visa Issued'), ('RES', 'Reserved')], default='AVA', max_length=3),
        ),
    ]
