# Generated by Django 6.0.5 on 2026-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_clientselection_booking_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientselection',
            name='notes',
        ),
        migrations.AddField(
            model_name='clientselection',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
