# Generated by Django 6.0.5 on 2026-05-20 14:36

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_remove_clientselection_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='visa_document',
            field=models.FileField(blank=True, help_text='Upload visa copy or related documents', null=True, upload_to=candidates.models.document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
